# Generated by Django 4.2.13 on 2025-03-05 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crashmanager', '0017_buckethit_unique_buckethits_per_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='BucketStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=0)),
                ('quality', models.IntegerField(null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crashmanager.bucket')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crashmanager.tool')),
            ],
        ),
        migrations.AddConstraint(
            model_name='bucketstatistics',
            constraint=models.UniqueConstraint(fields=('bucket', 'tool'), name='unique_bucketstats_per_tool'),
        ),
    ]
